kind: Pod
apiVersion: v1
metadata:
  name: rbd-pod
  namespace: ns1
spec:
  containers:
  - name: nginx-web
    image: nginx:alpine
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-storage
  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: rbd-pvc